### ISSUE TITLE
About the directory structure

### ISSUE THREAD

**Issue by hekunYNU** [mindflow-institue/annotation_free_fewshot#1]
Hello, can you provide the directory structure of the preprocessed dataset, thank you

**Comment by hekunYNU** [comment]
There is also the corresponding pre-training weight file, the original logs folder fss_weightsnew.pt can be given

**Comment by rezazad68** [comment]
Thanks for your interest in our work. Please apply the preprocessing step to generate the annotation mask. The preprocessing algorithm should generate a new mask in the same folder with the image name (like the gt). We will update the readme file soon to address this issue more clearly.
